# fly.toml file generated for ecommerce-portfolio on 2023-01-29T11:57:26+09:00

app = "ecommerce-portfolio"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.0"

[env]
  APP_NAME = "ecommerce-portfolio"
  APP_URL = "https://ecommerce-portfolio.fly.dev"
  SANCTUM_STATEFUL_DOMAINS = "ecommerce-portfolio.fly.dev"
  BROADCAST_DRIVER = "log"
  SESSION_LIFETIME = "1440"
  CASHIER_CURRENCY = "jpy"
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  DB_HOST = "ap-northeast.connect.psdb.cloud"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"
  MAIL_MAILER = "smtp"
  MAIL_HOST = "smtp.mailtrap.io"
  MAIL_PORT = "2525"
  MAIL_ENCRYPTION = "tls"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
